name: CI


env:
  AWS_REGION: us-east-1                  # set this to your preferred AWS region, e.g. us-west-1
  QDRANT_URL: ${{ secrets.QDRANT_URL }}  # set this to your Qdrant URL, e.g. https://qdrant.yourdomain.com
  QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}  # set this to your Qdrant API key, e.g. 1234567890abcdef1234567890abcdef

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'files/**'
      - 'documents/**'
      - '.gitingore'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'files/**'
      - 'documents/**'
      - '.gitingore'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Configure AWS credentials (For test API calls to AWS Bedrock)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pipx install poetry
          poetry install
        
      - name: Run format
        run: make format

      - name: Run lint
        run:  make lint
      
      - name: Run tests
        run:  make test
